commit with update on jenkinsfile of front 8

diff --git a/Ing2-proto/proto-front/Jenkinsfile b/Ing2-proto/proto-front/Jenkinsfile
--- a/Ing2-proto/proto-front/Jenkinsfile
+++ b/Ing2-proto/proto-front/Jenkinsfile
@@ -8,7 +8,7 @@ pipeline {
         stage('Cloning the repository') {
             agent {
                 docker {
-                     image 'ecotracer/front-agent'
+                    image 'ecotracer/front-agent'
                     args '--user root --entrypoint=""'
                 }
             }
@@ -27,20 +27,83 @@ pipeline {
             steps {
                 script {
                     sh '''
-                        ls -la
-
                         rm -rf node_modules package-lock.json
                         npm cache clean --force
-                        node --version
-
                         npm install --no-optional
                         npm install rollup --save-dev
-                        npm --version
                         npm run build
-                        ls -la
                     '''
                 }
             }
+        }
+
+        stage("Archive artifact") {
+            agent {
+                docker {
+                    image 'ecotracer/front-agent'
+                    args '--user root'
+                }
+            }
+            steps {
+                archiveArtifacts artifacts: "dist,Dockerfile", allowEmptyArchive: false
+            }
+        }
+
+        stage("Building Docker Image") {
+            agent {
+                docker {
+                    image 'ecotracer/dind'
+                    args '--user root --restart always -v /var/run/docker.sock:/var/run/docker.sock --entrypoint=""'
+                }
+            }
+            steps {
+                script {
+                    sh 'docker build -t ${REGISTRY_URL}/${IMAGE_NAME} .'
+                }
+            }
+        }
+
+        stage("Pushing Image to the registry") {
+            agent {
+                docker {
+                    image 'ecotracer/dind'
+                    args '--user root --restart always -v /var/run/docker.sock:/var/run/docker.sock --entrypoint=""'
+                }
+            }
+            steps {
+                withCredentials([usernamePassword(credentialsId: 'registry', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
+                    sh '''
+                        docker login ${REGISTRY_URL} -u $USERNAME -p $PASSWORD
+                        docker push ${REGISTRY_URL}/${IMAGE_NAME}
+                    '''
+                }
+            }
+        }
+
+        stage("Deploy to the front server") {
+            agent {
+                docker {
+                    image 'ecotracer/dind'
+                    args '--user root --restart always -v /var/run/docker.sock:/var/run/docker.sock --entrypoint=""'
+                }
+            }
+            steps {
+                sshagent(['frontend']) {
+                    sh """
+                        ssh -o StrictHostKeyChecking=no "${env.REMOTE_USER}"@"${env.REMOTE_HOST}" "docker stop frontend || true && docker rm frontend || true"
+                        ssh -o StrictHostKeyChecking=no "${env.REMOTE_USER}"@"${env.REMOTE_HOST}" "docker rmi -f ${REGISTRY_URL}/${IMAGE_NAME} && docker run -d --name frontend --network host -e API=${API} ${REGISTRY_URL}/${IMAGE_NAME}"
+                    """
+                }
+            }
+        }
+    }
+
+    post {
+        success {
+            echo 'Deployment completed successfully!'
+        }
+        failure {
+            echo 'Deployment failed. Please check the logs.'
         }
     }
 }
